hyper 0.13 -> 0.14, tonic 0.2 -> 1.0
akshayknarayan/hyper-unix-connector pull request #3
Opened 2020-12-25 06:54 UTC by amilkov3

2020-12-25 16:56 UTC, akshayknarayan requested changes
Thanks! Looks like the tests still need to be fixed?

2020-12-26 02:32 UTC, amilkov3 commented
Totally slipped my mind. Fixed

2020-12-26 16:01 UTC, merged

2020-12-26 16:01 UTC, akshayknarayan commented
Great, looks good. Resolves #2

2020-12-26 19:11 UTC, fanatid commented on Cargo.toml
> +hyper = { version = "0.14", features = ["full"] }
Do we really need `features = ["full"]`?

2020-12-26 20:09 UTC, fanatid commented on Cargo.toml
> +hyper = { version = "0.14", features = ["full"] }
I created pull request with removing not required features: #4